### ISSUE TITLE
"SQLITE_ERROR"が発生

### ISSUE THREAD

**Issue by neet34** [incompetence33/uma_js#1]
**わからなかったこと**
setup_ubuntu_zsh.shを使って、環境構築を行いました。
bun uma.jsを実行し、「音声、１、c:、wav」と選択をすると、
下記のエラーが出ます。（uma_js\output\sound_wav内には空のcというフォルダができます。）

進捗 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░] 0% | 0/1882 | スキップ: 0 | 存在なし: 0error: a
 errno: 1
 code: "SQLITE_ERROR"

**試したこと**
・WSL上の環境の再セットアップを数回したが、同じエラーが出る。
・bun uma.jsを実行後、別の選択肢を選んでも同じエラーが出る。
・同環境にてuma.shは動き、.wavファイルは出力されました。

**環境**
- OS: Windows 11 Home10.0.22621 N/A ビルド 22621
- WSL2 Ubuntu 22.04.3 LTS \n \l

**補足**
よろしくお願いします。

**Comment by incompetence33** [comment]
そのエラーは当方でも出ていた事があったのですが、power shellで
```powershell
wsl --shutdown
```
を実行してwslを一回落とすと直ったような気がします。
それでもだめなら一応「node.js」を使うことで解決できます。
が、bunでうまくいく方法を確立できるよう色々と考えてみようと思います。

**Comment by neet34** [comment]
すみませんが、powershellでコマンド実行してみましたが、エラーが再現してしまいました。
また、node.jsをインストールしてみたのですが、エラーが出てしまいました。
bunの時と似ていますが、コメントが変わったので添付しました。
![image](https://github.com/incompetence33/uma_js/assets/157908435/3bd56509-bc45-4be7-83ef-e4cc50016da1)

自分のやり方がいけないのかもしれないので、また時間をおいてためしてみます。
ありがとうございました。

**Comment by incompetence33** [comment]
そのエラー画像のお陰でエラーの原因がわかりました。
完全にこちらの落ち度です。申し訳ありません。
コードを修正しましたのでgit pullで更新してもう一度実行してみてください。

**Comment by incompetence33** [comment]
加えて、環境構築スクリプトも修正すべき点がありました。
```sh
curl -Lo ~/.zshrc "https://raw.githubusercontent.com/incompetence33/uma_js/master/%E7%92%B0%E5%A2%83%E6%A7%8B%E7%AF%89/.zshrc"
curl -Lo ~/.myfunctions "https://raw.githubusercontent.com/incompetence33/uma_js/master/%E7%92%B0%E5%A2%83%E6%A7%8B%E7%AF%89/.myfunctions"
```
これを実行すればShellがまともになると思います……
無能で申し訳ないです。

**Comment by neet34** [comment]
ご対応ありがとうございます。
修正してもらったファイルを利用したところエラーが解消され、正常動作しました。

またシェルも使いやすくなりました。
![image](https://github.com/incompetence33/uma_js/assets/157908435/4dc831ec-3990-4dbc-b159-97f3814db0b3)

ありがとうございました！
