### ISSUE TITLE
使い方がわからない

### ISSUE THREAD

**Issue by Sharke06** [incompetence33/uma_js#2]
**わからなかったこと**
環境構築のところにあるREADMEに書いてあったコードを実行してもPermission deniedとなります。
![image](https://github.com/incompetence33/uma_js/assets/171571873/440460cf-d18f-4b6f-a27d-76a1a2b68fda)

**試したこと**
sudoでやってみました。

**環境**
- OS: win11
- ubuntu: Microsoft store のやつ

**補足**
初めてubuntuを触るので全く使い方がわかりません。
軽く調べましたが全く理解できません。
ご迷惑をおかけします

**Comment by incompetence33** [comment]
本当ですね……
申し訳ないです。
正しくは
```bash
curl -Lo ~/setup_ubuntu_zsh.sh 'https://raw.githubusercontent.com/incompetence33/uma_js/master/%E7%92%B0%E5%A2%83%E6%A7%8B%E7%AF%89/setup_ubuntu_zsh.sh' && chmod 777 ~/setup_ubuntu_zsh.sh  && ~/setup_ubuntu_zsh.sh
```
ですね(`chmod 777 ~/setup_ubuntu_zsh.sh`をすることで実行権限を付与する過程がなかった)。
お手数おかけします。

**Comment by Sharke06** [comment]
ありがとうございます！
環境の構築はできたと思うのですが、進めていくと
![image](https://github.com/incompetence33/uma_js/assets/171571873/6b878ec2-3381-47af-98a4-7e1167e8eb11)
こんな風に No such file or directoryとなります、、、

**Comment by incompetence33** [comment]
ゲームの方はインストールされていますか？
また、一括ダウンロードして一度ゲームを開始しないとうまくいきません。

**Comment by Sharke06** [comment]
ゲームのほうのインストールは終わってると思いますが....
なぜでしょうか...

**Comment by incompetence33** [comment]
もしかしてインストール場所はCドライブ以外ですか？  
その場合の処理を書いていないのでもしそのようでしたら私の方で修正が必要です。

**Comment by Sharke06** [comment]
Cドライブにファイル作ってそこに入れてますね、

C:\uma\uma_js-master\環境構築\uma_js

**Comment by incompetence33** [comment]
ゲームのインストール位置のことです。
`C/Users/ユーザー名/AppData/LocalLow/Cygames/umamusume`
を検索位置にしているのでそれ以外にゲームをインストールしている場合うまくデータが取得できないのでエラーが発生する可能性があります。

**Comment by Sharke06** [comment]
C:\Users\xxxx\AppData\LocalLow\Cygames\umamusume
に25GBぐらいのデータあるのでちゃんと入ってるっぽいんですが、

**Comment by incompetence33** [comment]
なるほど、それならインストール場所が原因ではないようですね……
このコードを実行すると
![image](https://github.com/incompetence33/uma_js/assets/89658872/c58e1a55-2d38-4f56-8652-c35b1afaf2cb)
このように4つオプションを選択させられると思うのですが、先のスクリーンショットにはオプションが2つしか表示されていませんでした。
これは2つ目のオプションを選択後にコードがエラーを起こしたということなのでしょうか？

**Comment by Sharke06** [comment]
そうです！並列処理数の入力をした後にエラーはいて止まっちゃいます

**Comment by incompetence33** [comment]
一応確認なのですが、
`C:\Users\xxxx\AppData\LocalLow\Cygames\umamusume`
に`meta`という70MBくらいのファイルは存在しますか？

**Comment by Sharke06** [comment]
![image](https://github.com/incompetence33/uma_js/assets/171571873/8c3052ba-21fd-484d-b97a-69b6a05e69c0)
これですよね、？

**Comment by incompetence33** [comment]
んー……
あるんですね……
すると……？？
他に考えられるのは、先程このスクリプトのインストール場所は
`C:\uma\uma_js-master\環境構築\uma_js`
とおっしゃっていましたが、実際にはubuntu内の
`/home/salt/uma_js`
となっているようです。

実際の作業場所で
```bash
bun install
```
が行われていないというケースは考えられるかもしれません。
もし、そうなら試してみてください。
それでもダメな場合、一度現在インストールしているこのスクリプトを削除し、
```bash
#例: C:\uma を作業場所とする場合
#C:\uma 内のuma_jsを何らかの方法で削除してからubuntuで
cd /mnt/c/uma
git clone --depth 1 https://github.com/incompetence33/uma_js
cd uma_js
bun install
bun run ./uma.js
```
と、このようにやってみてください。

**Comment by Sharke06** [comment]
やはり 
/mnt/c/uma/uma_js/output/キャラID.txt
/mnt/c/uma/uma_js/output/ライブID.txt
が存在しないといわれます、

**Comment by Sharke06** [comment]
すみません解決しました....
→キーで選択しないといけないのを知らずに進んでしまっていたのが原因ったようです。。。
迷惑をおかけしました。本当に申し訳ないです

**Comment by incompetence33** [comment]
ああ、そういうことでしたかー
スペースキーでも選択できます！
解決されたみたいでよかったです！
