### ISSUE TITLE
sqlite3インストール時の不具合

### ISSUE THREAD

**Issue by drydeuterium** [incompetence33/uma_js#3]
**わからなかったこと**
uma.jsのインストール時のbun installにて、sqlite3をinstallする時にprebuild-install warn install Request timed outと表示されました。
エラー文はinstall script from "sqlite3" exited with 1でした。
![image](https://github.com/incompetence33/uma_js/assets/68512511/504780fa-6035-4b75-86ce-3a536110f8a0)

**Comment by incompetence33** [comment]
エラーメッセージを見たところ、パッケージをインターネット上から取得するするときに時間がかかりすぎてタイムアウトしているようです。
これは私の方でなんとかできる問題ではないので、VPNやプロキシを利用している場合一時的に無効にしたり、少し時間をおいて再トライしたりしてみてください。

**Comment by incompetence33** [comment]
と思ったのですが、使ってるライブラリが古いものだったので、bunの組み込みのものに変更することでインストールを不要にしました。
```bash
git pull
```
してアップデートしてもう一度試してみてください。

**Comment by drydeuterium** [comment]
ありがとうございます。無事インストール成功し、音源も変換できました。お手数おかけしました。
